
services:
  bot:
    build: .
    container_name: tg_bot
    depends_on:
      - redis
    networks:
      - bot_network

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bot_network

volumes:
  redis_data:

networks:
  bot_network:
    driver: bridge